code4startupPro/config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'}, 
              :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
              
  get 'pages/about'
  get '/myprojects' => 'project#list'
  post '/free' => 'charge#free'
  post '/pay' => 'charge#pay'

  root 'project#index'

  resources :project do 
    resources :task, only: [:show]
  end

  resources :project do 
    resources :reviews, only: [:create, :destroy]
  end

end

code4startupPro/app/views/shares/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type= "text/javascript">
	<% resource.errors.full_messages.each do |msg| %>
		toastr.error('<%= msg %>')
	<% end %>
	</script>
<% end %>

code4startupPro/app/views/shares/_footer.html.erb
<footer class="page-footer blue-grey darken-3">
	  <div class="container">
	    <div class="row">
	      <div class="col l6 s12">
	        <h5 class="white-text">ProCode4Startup</h5>
	        <p class="grey-text text-lighten-4">Here is some information about ProCode4Startup. I am takingn this course by Leo Trieu to help learn about Ruby on </p>
	      </div>
	      <div class="col l4 offset-l2 s12">
	        <h5 class="white-text">Links</h5>
	        <ul>
	          <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
	          <li><a classs="grey-text text-lighten-3" href="#!">Facebook</a></li>
	          <li><a class="grey-text text-lighten-3" href="#!">Google Plus</a></li>
	          
	        </ul>
	      </div>
	    </div>
	  </div>
	  <div class="footer-copyright">
	    <div class="container">
	    © 2015 Copyright Pro4CodeStartup
	
	    <%= link_to "About Us", pages_about_path, :class => "grey-text text-lighten-4 right" %>
	    </div>
	  </div>
</footer>

code4startupPro/app/views/shares/_header.html.erb
<header>
	<!-- Dropdown for Nav bar -->
	<ul id="dropdown1" class="dropdown-content mask">
	  <li><%= link_to "My Profile", edit_user_registration_path %></li>

	  <li><%= link_to "My Projects", myprojects_path %></li>
	 
	  <li class="divider"></li>
	  <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
	</ul>
	<!-- we create two one for mobile and one for web -->
	<ul id="dropdown2" class="dropdown-content mask">
	  <li><%= link_to "My Profile", edit_user_registration_path %></li>
	  <li><%= link_to "My Projects", myprojects_path %></li>
	  <li class="divider"></li>
	  <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
	</ul>

	<nav class="blue-grey darken-3 z-depth-2">
		<div class="container">
			<div class="nav-wrapper">
		      <a href="#!" class="brand-logo">ProCode4Startup</a>
		      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
	
		      <ul class="right hide-on-med-and-down">
		        <li><%= link_to "Projects", root_path %></li>
		        <% if(!user_signed_in?) %>
		        	<li><%= link_to "Sign Up", new_user_registration_path %></li>
		        	<li><%= link_to "Login", new_user_session_path %></li>
		       	<% else %>
		        	<li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown1">
		        		<%= image_tag avatar_url(current_user), class: "circle responsive-image avatar-small" %>&nbsp;
		        		<%= current_user.email %><i class="mdi-navigation-arrow-drop-down right"></i></a>
		        	</li>
	        	<% end %>	
		      </ul>
		      <ul class="side-nav" id="mobile-demo">
		        <li><a href="#">Courses</a></li>
		        <% if(!user_signed_in?) %>
		        	<li><%= link_to "Sign Up", new_user_registration_path %></li>
		        	<li><%= link_to "Login", new_user_session_path %></li>
		       	<% else %>
		        	<li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown2">
		        		<%= image_tag avatar_url(current_user), class: "circle responsive-image avatar-small" %> &nbsp;

		        		<%= current_user.email %><i class="mdi-navigation-arrow-drop-down right"></i></a></li>
	        	<% end %>
		      </ul>
		    </div>
		</div>
		
		</nav>
</header>

code4startupPro/app/views/shares/_message.html.erb
<% unless flash.empty? %>
	<script type= "text/javascript">
	<% flash.each do |f| %>
		<% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
		toastr['<%= type %>']('<%= f[1] %>')
	<% end %>
	</script>
<% end %>