code4startupPro/config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'}, 
              :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
              
  get 'pages/about'
  get '/myprojects' => 'project#list'
  post '/free' => 'charge#free'
  post '/pay' => 'charge#pay'

  root 'project#index'

  resources :project do 
    resources :task, only: [:show]
  end

  resources :project do 
    resources :reviews, only: [:create, :destroy]
  end

end

code4startupPro/app/models/project.rb
class Project < ActiveRecord::Base
	extend FriendlyId
	friendly_id :name, use: [:slugged, :finders]

	has_many :tasks

	has_many :subscriptions
	has_many :users, through: :subscriptions

	has_many :reviews

	validates :name, presence: true, length: { maximum: 50 }
	validates :content, presence: true, length: { maximum: 1000 }
	validates :language, presence: true, length: { maximum: 100 }
	validates :price, presence: true, numericality: { only_integer: true }

	has_attached_file :image, :styles => { :medium => "680x300>", :thumb => "170x75>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  	def shortname
  		name.length > 25? name[0..25] + "..." : name
  	end

  	def average_rating
  		reviews.blank? ? 0 : reviews.average(:star).round(2)
  	end

  	def price_in_cents
  		price*100
  	end


end

code4startupPro/app/controllers/project_controller.rb
class ProjectController < ApplicationController
  
  before_action :authenticate_user!, only: [:list]

  def index
  	@projects = Project.all
  end

  def show
  	@project = Project.find(params[:id])
  	@tasks =  @project.tasks.order(:tag)
 
 	  @joined = false

		if !current_user.nil? && !current_user.projects.nil?
	  		@joined = current_user.projects.include?(@project)
		end

		@users = @project.users.order('created_at desc').first(10)

    @review = Review.new
    @reviews = @project.reviews

    @hasReview = @reviews.find_by(user_id: current_user.id) if current_user

  end

	def list
		if !current_user.nil?
			@projects = current_user.projects
		end
  end

end

code4startupPro/app/helpers/project_helper.rb
module ProjectHelper
end

code4startupPro/app/views/project/index.html.erb
<div class = "row" data-no-turbolink>
	<br/>

	<% @projects.each do |project| %>
		<%= link_to project do %>
		<div class="col s12 m6 l4">
			<div class="card">

				<div class="card-image waves-effect waves-block waves light">
					<%= image_tag project.image %>
				</div>

				<div class="card-content" style="height: 6em">
					<span class="card-title grey-text text-darken-4">
						<%= project.shortname %>
					</span>
				</div>
			</div>
		</div>
		<% end %>
	<% end %>
</div>

code4startupPro/app/views/project/list.html.erb
<h1>My Projects</h1>

<div class = "row" data-no-turbolink>
	<br/>

	<% if @projects.count > 0 %>

		<% @projects.each do |project| %>
			<%= link_to project do %>
			<div class="col s12 m6 l4">
				<div class="card">

					<div class="card-image waves-effect waves-block waves light">
						<%= image_tag project.image %>
					</div>

					<div class="card-content" style="height: 6em">
						<span class="card-title grey-text text-darken-4">
							<%= project.shortname %>
						</span>
					</div>
				</div>
			</div>
			<% end %>
		<% end %>
	<% else %>
		<div class="center">
			<h5>Currently you don't have any projects!</h5>
		</div>
		<%= link_to "Show me all Projects", root_path, class: "btn btn-warning" %>
	<% end %>
</div>

code4startupPro/app/views/project/show.html.erb
<% content_for :head do %>
	<title><%= @project.name %>| Pro4Code ></title>

	<!-- Twitter Card data -->
	<meta name="twitter:card" content="summary_large_image">
	<meta name="twitter:site" content="@caroline_louie">
	<meta name="twitter:creator" content="@caroline_louie">
	<meta name="twitter:title" content="<%= @project.name %>">
	<meta name="twitter:description" content="<%= @project.content %>">
	<meta name="twitter:image:src" content="<%= image_url @project.image %>">

	<!-- Open Graph Data -->
	<meta property="og:site_name" content="Pro4Code">
	<meta property="og:type" content="website">
	<meta property="og:title" content="<%= @project.name %>">
	<meta property="og:description" content="<%= @project.content %>">
	<meta property="og:image" content="<%= @project.image %>">
<% end %>

<div class = "row">
	<div class="col m4">
		<div class="card z-depth-2">
			<% if !@joined %>

			<div class="center">
				<h1>$<%= @project.price == 0? 'Free' : "#{@project.price}" %></h1>
			</div>
			<div class="card-action center">
				<div>
						<p><%= markdown(@project.github) %></p>	
				</div>

				<div> 
					<p>Languages used: <%= @project.language %></p>
				</div>
				<% if user_signed_in? %>

					<% if @project.price == 0 %>
						<%= form_tag free_path do %>
							<%= hidden_field_tag 'project_id', @project.id %>
							<button class="btn waves-effect waves-light pink darken-2">
								Take this Project
							</button>
						<% end %>
					<% else %>
						<%= form_tag pay_path, id:'chargeForm' do %>

							<script src="https://checkout.stripe.com/checkout.js"></script>

							<%= hidden_field_tag 'stripeToken' %>
							<%= hidden_field_tag 'stripeEmail' %>
							<%= hidden_field_tag 'project_id', @project.id %>

							<button id="customButton" type="button" class="btn pink darken-2">Take this Project</button><br/>

							<script>
							  var handler = StripeCheckout.configure({
							    key: '<%= ENV['STRIPE_PUBLIC_KEY'] %>',
							    token: function(token, arg) {
							    console.log(token.email, token.id);
							      $('#stripeToken').val(token.id);
							      $('#stripeEmail').val(token.email);
							      $('#chargeForm').submit();
							    }
							  });

							  $('#customButton').on('click', function(e) {
							    // Open Checkout with further options
							    handler.open({
							      name: 'Pro4Code',
							      description: '<%= @project.name %>',
							      amount: '<%= @project.price_in_cents %>',
							      email: '<%= current_user.email %>'
							    });
							    e.preventDefault();
							  });

							</script>
						<% end %>
					<% end %>

				<% else %>
					<%= link_to new_user_session_path do %>
						<button class="btn waves-effect waves-light pink darken-2">
							Take this Project
						</button>
					<% end %>
				<% end %>
			</div>

			<% else %>
			<div class="card-content center">
				<%= image_tag avatar_url(current_user), class: "circle responsive-image avatar-medium" %><br/>
				<h5><%= current_user.name %></h5>
			</div>
			<div class="card-action center">
				<div> 
					<p>Languages used: <%= @project.language %></p>
				</div>
				<% @users.each do |u| %>
					<span class="valign-wrapper">
						<%= image_tag avatar_url(u), class: "circle responsive-image avatar-small" %>&nbsp;
						<%= u.name %>
					</span><br/>
				<% end %>
			</div>

			<% end %>
		</div>




	</div>


	<div class="col m8">
		<div class="card z-depth-2">

			<div class="card-image">
				<%= image_tag @project.image %>
			</div>
			

				<div class="row">
				    <div class="col s12">
				      <ul class="tabs">
				        <li class="tab col s3"><a class="active" href="#about">About</a></li>
				        <li class="tab col s3"><a href="#videos">Videos</a></li>
				        <li class="tab col s3"><a href="#discussions">Discussions</a></li>
				      </ul>
				    </div>
				    <div id="about" class="col s12">
				    	<div class="card-content grey-text text-darken-4">
							<h5><%= @project.name %></h5>
							
							<span id="average_rating"></span>
							<p> <%= @reviews.count %> <%= @reviews.count > 1? "Reviews" : "Review" %> </p>
							<hr>
					    	<%= @project.content %>
					    	<h4>Reviews</h4>
							<div><%= render 'reviews/form' if @joined && !@hasReview %></div>	
							<div><%= render 'reviews/index' %> </div> 
						</div>
				    </div>
				    
				    <div id="videos" class="col s10 offset-s1">
				    	<div class="collection" data-no-turbolink>
						    <% @tasks.each do |task| %>
								<% if task.header %>
									<div class="collection-item active">
										<i class="mdi-social-school"> <%= task.title %></i>
									</div>
								<% else %>
									<%= link_to [task.project, task], class: "collection-item" do %>
										<%= task.title %>
									<% end %>
								<% end %>
							<% end %>
						</div>
				    </div>

				    <div id="discussions" class="col s10 offset-s1">
				    	<div id="disqus_thread"></div>
							<script type="text/javascript">
							    /* * * CONFIGURATION VARIABLES * * */
							    var disqus_shortname = 'clouie';

							    var disqus_identifier = '<%= @project.id %>';
							    
							    /* * * DON'T EDIT BELOW THIS LINE * * */
							    (function() {
							        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
							        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
							        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
							    })();
							</script>
							<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
				    </div>
				</div>
			</div>
		</div>
	</div>


<script>
	$(document).ready(function(){
	    $('ul.tabs').tabs();

		$('#average_rating').raty({
			path: '/assets',
			readOnly: true,
			score: <%= @project.average_rating %>
		});
	 });
</script>